# Use a Node.js base image
FROM node:21-bullseye

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the entire app directory to the container
COPY . .

# Expose the port your Svelte app is running on (default is 5000)
EXPOSE 5000

# Start your Svelte app in development mode
CMD ["npm", "run", "dev"]
