#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/_common"

EXT_ID="${1:-1001}"

#DETAILS="$(printf '{"kind":"Min","first_name":"%s","last_name":"%s","ext_id":"%s"}' "$FIRST_NAME" "$LAST_NAME" "$EXT_ID")"

#DETAILS="$(printf '{"ccode": "%s" }' "$EXT_ID")"

#curl -H "Content-Type: application/json"  POST "https://100.79.241.8/fr/enrollment/create" -d '{ "command": "enroll",  "candidates" : [{ "ccode": "${EXT_ID}" }] }'

#curl -H "Content-Type: application/json"  POST "http://localhost:3000/fr/enrollment/create" -d '{ "command": "enroll",  "candidates" : [{ "ccode": "${EXT_ID}" }] }'

jq -n --arg ext "$EXT_ID" '{
  command: "enroll",
  candidates: [{ ccode: $ext }]
}' | curl -H "Content-Type: application/json" \
     -X POST "http://localhost:3000/fr/enrollment/create" \
     -d @-
