#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/_common"

EXT_ID="${1:-1001}"

#DETAILS="$(printf '{"kind":"Min","first_name":"%s","last_name":"%s","ext_id":"%s"}' "$FIRST_NAME" "$LAST_NAME" "$EXT_ID")"

#DETAILS="$(printf '{"ccode": "%s" }' "$EXT_ID")"

curl -H "Content-Type: application/json"  POST "http://localhost:3000/fr/enrollment/create" -d '{ "command": "enroll",  "candidates" : [{ "ccode": "1001" }] }'
