#since we only have the option to pull the latest. Let's hold off on this.
#we'll continue to use the version we have that's been retagged and
#update manually. we don't want to pull down whatever new release everytime
#we start a deployment.
FROM ghcr.io/deepch/rtsptoweb
